feat: add initial gha
saritasa-nest/ksso pull request #3
Opened 2024-12-20 22:03 UTC by dmitry-mightydevops

2025-01-07 01:20 UTC, dmitry-mightydevops commented
@kseniyashaydurova @luciano-buono @KrawczowaKris this PR is ready for your review.

2025-01-08 14:12 UTC, luciano-buono requested changes

2025-01-08 14:12 UTC, luciano-buono commented on .github/workflows/build.yaml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

2025-01-08 14:12 UTC, luciano-buono commented on .github/workflows/build.yaml
> +        uses: actions/setup-python@v4
```suggestion
        uses: actions/setup-python@v5
```

2025-01-08 14:12 UTC, luciano-buono commented on .github/workflows/build.yaml
> +          echo "::set-output name=version::$version"
Can we use newer GITHUB_ENV variable instead?
    
```suggestion
          echo "version=$version" >> $GITHUB_ENV
```

2025-01-08 14:12 UTC, luciano-buono commented on .github/workflows/build.yaml
> +      - name: Build binary with nuitka
Why are you using this tool?
Is it the same as PyInstaller? Maybe we can add some comments here or in the readme for this decision

2025-01-08 14:12 UTC, luciano-buono commented on .github/workflows/build.yaml
> +        uses: actions/create-release@v1
This action is deprecated.

Maybe we can update it to https://github.com/ncipollo/release-action?

https://github.com/saritasa-nest/ats-dart-desktop/blob/b223e2bd6674cf44688218febc971cc68b00bfeb/.github/workflows/windows-build.yml#L216

2025-01-08 16:03 UTC, luciano-buono commented
Also, could you squash the commits before you merge?

2025-01-08 18:51 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +        uses: actions/checkout@v3
done

2025-01-08 18:51 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +        uses: actions/setup-python@v4
Done

2025-01-08 18:53 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +          echo "::set-output name=version::$version"
we need the older implementation due to the reference of **version** in the **release** job
```
 - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: ksso v${{ needs.build.outputs.version }}
          draft: false
          prerelease: false
```
which is not working with pure GITHUB_ENV

2025-01-08 18:54 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +      - name: Build binary with nuitka
Yes it's analog of pyinstaller.

2025-01-08 18:56 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +        uses: actions/create-release@v1
This will have to be done in a separate PR

2025-01-08 18:58 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +      - name: Build binary with nuitka
added small comment

2025-01-08 18:58 UTC, dmitry-mightydevops commented
@luciano-buono 
> Also, could you squash the commits before you merge?
will do!

2025-01-08 19:04 UTC, luciano-buono commented on .github/workflows/build.yaml
> +          echo "::set-output name=version::$version"
GITHUB_OUTPUT is also available, but you may find the same issue:

`echo "{name}={value}" >> "$GITHUB_OUTPUT"`

2025-01-08 19:04 UTC, luciano-buono approved these changes

2025-01-08 19:16 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +          echo "::set-output name=version::$version"
Ok let me try

2025-01-08 19:35 UTC, dmitry-mightydevops commented on .github/workflows/build.yaml
> +          echo "::set-output name=version::$version"
it worked! Thank you Luciano!

2025-01-09 06:02 UTC, udaltsovra approved these changes

2025-01-13 06:49 UTC, kseniyashaydurova approved these changes

2025-01-13 06:49 UTC, kseniyashaydurova commented on .github/pull_request_template.md
> +Task: [MBARR-???](https://saritasa.atlassian.net/browse/SD-???)
```suggestion
Task: [SD-???](https://saritasa.atlassian.net/browse/SD-???)
```

2025-01-13 08:53 UTC, KrawczowaKris approved these changes

2025-01-14 18:46 UTC, merged